### ISSUE TITLE
Create a public demonstration repository named `eoapi-template`

### ISSUE THREAD

**Issue by emileten** [developmentseed/eoapi-cdk#47]
Create an external repository that demonstrates the usage of the `cdk-pgstac` constructs, and that is based off of https://github.com/developmentseed/aws-asdi-pgstac. 

Reference discussion : https://github.com/developmentseed/eoAPI/issues/94.

This 'demonstration' deployment can be used for https://github.com/developmentseed/cdk-pgstac/issues/13. 

I am planning to have this written in python for wider accessibility, unlike `aws-asdi-pgstac`, and to first submit it as a PR here in a separate folder for easy review and then put it in an external repository. 

cc @vincentsarago @alukach @sharkinsspatial

**Comment by sharkinsspatial** [comment]
Based on @emileten 's questions in the Slack thread, I'm wondering if we should make this an independent repo or just a testing subdirectory here?  I'm leaning towards an independent repo.  @emileten Definitely agree that we should do this in Python for accessibility 👍 .  Let me know when you you have a PR for this and I'm happy to spruce up the documentation a bit.

**Comment by emileten** [comment]
Sounds good @sharkinsspatial. I am working off of the `feature/integration-tests` branch for now but once it's ready I will move it to an external repository.

**Comment by alukach** [comment]
To avoid conflicts with https://github.com/developmentseed/cdk-pgstac/issues/49, it may be wise to make the naming clear that this is an demonstration of using `cdk-pgstac`.  Perhaps something like `eoapi-app` or `eoapi-app`?  I don't know it's it's critical that we include the backing lib (cdk) in the name of the project as that's more of an implementation detail at that point.

**Comment by vincentsarago** [comment]
`eoapi-app` sounds fine to me or `eoapi-serverless-stack` 😅

**Comment by emileten** [comment]
https://github.com/developmentseed/eoapi-template
