### ISSUE TITLE
Rename library to eoapi-cdk

### ISSUE THREAD

**Issue by sharkinsspatial** [developmentseed/eoapi-cdk#49]
As discussed on internal Slack threads.  To provide consistency across the different IAC options and tie everything nicely together with [eoAPI](https://github.com/developmentseed/eoAPI) let's consider renaming the package to `eoapi-cdk`.

**Comment by sharkinsspatial** [comment]
@alukach Curious to hear your thoughts/ideas around this?

**Comment by alukach** [comment]
Sounds like a fine idea to me!  Should we rename packages in NPM/PyPi or create new packages?  The latter would be a nice way to get a fresh start 🌸

**Comment by vincentsarago** [comment]
> The latter would be a nice way to get a fresh start

👍

**Comment by vincentsarago** [comment]
I think we can close this one?
