### ISSUE TITLE
Add custom parameter mapping when using custom API domain

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/eoapi-cdk#75]
When using custom API domain in API Gateway the FastAPI application (starlette) will still receive the api gateway hostname and thus use it internally (e.g if you have an endpoint that construct other endpoint url, it will return the API gateway url instead of you custom domain name)

e.g titiler 
```python
import httpx

resp = httpx.get("https://stac.eoapi.dev")
print(resp.json()["links"][2]

>>      {
      "rel": "data",
      "type": "application/json",
      "href": "https://stac.eoapi.dev/collections"
    }
```

☝️ this is giving the correct result (stac.eoapi.dev hostname) because I've manually added custom parameter mapping in the API Gateway console:

<img width="1651" alt="Screenshot 2023-10-05 at 1 00 59 PM" src="https://github.com/developmentseed/eoapi-cdk/assets/10407788/8361dd6e-7849-4ec8-98db-e57659e78f84">

I believe we can automatically create this in 👇 

https://github.com/developmentseed/eoapi-cdk/blob/a1081a22e034d50f89d248d36844d598d45d5c69/lib/stac-api/index.ts#L60-L65

with: 
https://constructs.dev/packages/@aws-cdk/aws-apigatewayv2/v/1.204.0/api/ParameterMapping?lang=typescript

```js
    const stacApi = new HttpApi(this, `${Stack.of(this).stackName}-stac-api`, {
      defaultDomainMapping: props.stacApiDomainName ? { 
        domainName: props.stacApiDomainName
      } : undefined,
      defaultIntegration: new HttpLambdaIntegration("integration", this.stacApiLambdaFunction, parameterMapping = props.stacApiDomainName ? {new ParameterMapping().overwriteHeader('host', MappingValue.requestHeader(props.stacApiDomainName))} : undefined),
    });
```

**Comment by slesaad** [comment]
@vincentsarago i tested this with the ghg center backend, and `MappingValue.requestHeader` threw an error

```
```
