### ISSUE TITLE
Support DockerImageFunction in lambda deployments

### ISSUE THREAD

**Issue by emileten** [developmentseed/eoapi-cdk#78]
Adding support for [DockerImageFunction](https://github.com/developmentseed/eoapi-cdk/pull/74/commits/dbcada8cf65e3264a71144c660e9a688db9f1e59) would allow users to pass runtimes associated with assets > 250 MB. As of now we deploy all the lambdas using [Function](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Function.html). See this comment https://github.com/developmentseed/eoapi-cdk/pull/74#discussion_r1349381411. cc @sharkinsspatial.

**Comment by vincentsarago** [comment]
FYI: DockerImage functions are really slowwwwwww and should be avoided!
IMO if user do need bigger package they might be better served with an EFS storage where they store the big libraries!

**Comment by emileten** [comment]
Does this speed difference matter for all the applications in this stack ? I guess yes, in which case we can close

**Comment by vincentsarago** [comment]
> Does this speed difference matter for all the applications in this stack ?

I think yes
