### ISSUE TITLE
[STAC-Browser] enable `buildTileUrlTemplate` override 

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/eoapi-cdk#83]
If the stack contains a Raster service and a STAC-Browser it will make sense to use the internal raster tiler

https://github.com/developmentseed/eoapi-cdk/blob/b704c6e052170b6e3be423ccebdd5db7ffc97376/lib/stac-browser/index.ts#L106

**Comment by emileten** [comment]
allowed for this in https://github.com/developmentseed/eoapi-cdk/pull/84
